#!/usr/bin/env bash
set -Eeuo pipefail

# Unified setup for the PREOF/FRER-inspired BESS-UPF + TRex + receiver testbed.
# Roles:
#   --setup upf       MICH, BESS-UPF DPDK host
#   --setup trex      UCSD, TRex traffic generator host
#   --setup receiver  FIU, Linux receiver/deduplicator host
#
# Defaults follow the validated README addressing plan:
#   N3/control side: TRex 192.168.70.2 -> UPF 192.168.70.1
#   N6/receiver side: UPF 192.168.80.1 -> receiver 192.168.80.2
#   PFCP/control side: TRex 192.168.90.2 -> UPF 192.168.90.1
#
# Typical usage for the current FABRIC topology discovered on 2026-05-04:
#   receiver FIU: sudo ./setup_preof_testbed_fabric_v2.sh --setup receiver
#   UPF MICH:     sudo ./setup_preof_testbed_fabric_v2.sh --setup upf
#   TRex UCSD:    sudo ./setup_preof_testbed_fabric_v2.sh --setup trex
#
# Discovered default mapping:
#   UCSD/TRex    N3= enp7s0np0, PFCP/control= enp9s0
#   MICH/UPF     N3= enp8s0np0, N6= enp9s0np0, PFCP/control= enp7s0
#   FIU/Receiver N6= enp8s0np0
#
# Notes:
#   1. This script intentionally does NOT clone pfcpsim, because the patched repository/image is external.
#   2. For TRex, a one-port N3 configuration is generated by default. If your TRex build requires two ports,
#      pass --trex-port2-if IFACE and --trex-port2-dst-mac MAC.
#   3. The script flushes and assigns IP addresses on the interfaces passed to it.

ROLE=""

# Interface defaults are role-specific and are applied after --setup is parsed.
# They match the current FABRIC topology discovered on 2026-05-04.
N3_IF=""
N6_IF=""
CTRL_IF=""
TREX_PORT2_IF=""

# IP defaults.
UPF_N3_IP="192.168.70.1"
TREX_N3_IP="192.168.70.2"
UPF_N6_IP="192.168.80.1"
RECEIVER_N6_IP="192.168.80.2"
UPF_CTRL_IP="192.168.90.1"
TREX_CTRL_IP="192.168.90.2"

# MACs, can be supplied or discovered by ARP when possible.
# Defaults below match the current FABRIC topology discovered on 2026-05-04.
UPF_N3_MAC=""
RECEIVER_N6_MAC=""
TREX_PORT2_DST_MAC=""

# Software versions.
TREX_VERSION="v3.08"
TREX_TARBALL_URL="https://trex-tgn.cisco.com/trex/release/v3.08.tar.gz"
MLNX_OFED_URL="https://www.mellanox.com/downloads/ofed/MLNX_OFED-5.9-0.5.6.0/MLNX_OFED_LINUX-5.9-0.5.6.0-ubuntu22.04-x86_64.tgz"
MLNX_OFED_DIR="MLNX_OFED_LINUX-5.9-0.5.6.0-ubuntu22.04-x86_64"

HUGEPAGES="1024"
PERSIST_NETPLAN="false"
START_UPF="true"
INSTALL_OFED="true"

WORKDIR="/opt/preof-testbed"
BESS_WORKDIR="/opt/bess-upf"
TREX_DIR="/opt/trex/v3.08"

usage() {
  cat <<USAGE
Usage:
  sudo $0 --setup upf|trex|receiver [options]

Common options:
  --n3-if IFACE                 N3 traffic interface, role-specific default
  --n6-if IFACE                 N6 traffic interface, role-specific default
  --ctrl-if IFACE               PFCP/control interface, role-specific default
  --upf-n3-ip IP                default ${UPF_N3_IP}
  --trex-n3-ip IP               default ${TREX_N3_IP}
  --upf-n6-ip IP                default ${UPF_N6_IP}
  --receiver-n6-ip IP           default ${RECEIVER_N6_IP}
  --upf-ctrl-ip IP              default ${UPF_CTRL_IP}
  --trex-ctrl-ip IP             default ${TREX_CTRL_IP}
  --hugepages N                 default ${HUGEPAGES}
  --persist-netplan             write a simple netplan file for the selected role
  --skip-ofed                   skip MLNX OFED userspace installation

UPF-specific:
  --receiver-n6-mac MAC         receiver N6 MAC, used for static neighbor/route
  --no-start-upf                prepare images/configs but do not start BESS/pfcpiface

TRex-specific:
  --upf-n3-mac MAC              UPF N3 destination MAC for /etc/trex_cfg.yaml
  --trex-port2-if IFACE         optional second TRex port if your TRex requires paired ports
  --trex-port2-dst-mac MAC      destination MAC for optional second TRex port

Examples for the current topology:
  sudo $0 --setup receiver
  sudo $0 --setup upf
  sudo $0 --setup trex

Equivalent explicit form:
  sudo $0 --setup receiver --n6-if enp8s0np0
  sudo $0 --setup upf --n3-if enp8s0np0 --n6-if enp9s0np0 --ctrl-if enp7s0 --receiver-n6-mac 10:70:fd:c0:ef:40
  sudo $0 --setup trex --n3-if enp7s0np0 --ctrl-if enp9s0 --upf-n3-mac b8:ce:f6:19:09:32
USAGE
}

log() { echo "[preof-setup] $*"; }
warn() { echo "[preof-setup][WARN] $*" >&2; }
fatal() { echo "[preof-setup][ERROR] $*" >&2; exit 1; }

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    fatal "Run as root, for example: sudo $0 ..."
  fi
}

apply_role_defaults() {
  case "${ROLE}" in
    receiver)
      : "${N6_IF:=enp8s0np0}"
      # Receiver N6 observed on FIU:
      #   enp8s0np0 MAC 10:70:fd:c0:ef:40, PCI 0000:08:00.0
      ;;
    upf)
      : "${N3_IF:=enp8s0np0}"
      : "${N6_IF:=enp9s0np0}"
      : "${CTRL_IF:=enp7s0}"
      : "${RECEIVER_N6_MAC:=10:70:fd:c0:ef:40}"
      # UPF observed on MICH:
      #   N3/access     enp8s0np0 MAC b8:ce:f6:19:09:32, PCI 0000:08:00.0
      #   N6/core       enp9s0np0 MAC b8:ce:f6:19:09:33, PCI 0000:09:00.0
      #   PFCP/control  enp7s0    MAC 02:0b:7f:65:7b:51, PCI 0000:07:00.0
      ;;
    trex)
      : "${N3_IF:=enp7s0np0}"
      : "${CTRL_IF:=enp9s0}"
      : "${UPF_N3_MAC:=b8:ce:f6:19:09:32}"
      # TRex observed on UCSD:
      #   N3            enp7s0np0 MAC 10:70:fd:c0:ef:a0, PCI 0000:07:00.0
      #   PFCP/control  enp9s0    MAC 16:e7:68:5c:0e:b8, PCI 0000:09:00.0
      ;;
  esac
}

print_effective_topology() {
  log "Effective topology for role ${ROLE}"
  case "${ROLE}" in
    receiver)
      echo "  Receiver N6: ${N6_IF} -> ${RECEIVER_N6_IP}/24"
      ;;
    upf)
      echo "  UPF N3/access:     ${N3_IF} -> ${UPF_N3_IP}/24"
      echo "  UPF N6/core:       ${N6_IF} -> ${UPF_N6_IP}/24"
      echo "  UPF PFCP/control:  ${CTRL_IF} -> ${UPF_CTRL_IP}/24"
      echo "  Receiver N6 MAC:   ${RECEIVER_N6_MAC:-auto-discover}"
      ;;
    trex)
      echo "  TRex N3:           ${N3_IF} -> ${TREX_N3_IP}/24"
      echo "  TRex PFCP/control: ${CTRL_IF} -> ${TREX_CTRL_IP}/24"
      echo "  UPF N3 MAC:        ${UPF_N3_MAC:-auto-discover}"
      ;;
  esac
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --setup) ROLE="${2:-}"; shift 2 ;;
      --n3-if) N3_IF="${2:-}"; shift 2 ;;
      --n6-if) N6_IF="${2:-}"; shift 2 ;;
      --ctrl-if) CTRL_IF="${2:-}"; shift 2 ;;
      --trex-port2-if) TREX_PORT2_IF="${2:-}"; shift 2 ;;
      --trex-port2-dst-mac) TREX_PORT2_DST_MAC="${2:-}"; shift 2 ;;
      --upf-n3-ip) UPF_N3_IP="${2:-}"; shift 2 ;;
      --trex-n3-ip) TREX_N3_IP="${2:-}"; shift 2 ;;
      --upf-n6-ip) UPF_N6_IP="${2:-}"; shift 2 ;;
      --receiver-n6-ip) RECEIVER_N6_IP="${2:-}"; shift 2 ;;
      --upf-ctrl-ip) UPF_CTRL_IP="${2:-}"; shift 2 ;;
      --trex-ctrl-ip) TREX_CTRL_IP="${2:-}"; shift 2 ;;
      --upf-n3-mac) UPF_N3_MAC="${2:-}"; shift 2 ;;
      --receiver-n6-mac) RECEIVER_N6_MAC="${2:-}"; shift 2 ;;
      --hugepages) HUGEPAGES="${2:-}"; shift 2 ;;
      --persist-netplan) PERSIST_NETPLAN="true"; shift ;;
      --skip-ofed) INSTALL_OFED="false"; shift ;;
      --no-start-upf) START_UPF="false"; shift ;;
      -h|--help) usage; exit 0 ;;
      *) fatal "Unknown argument: $1" ;;
    esac
  done

  case "${ROLE}" in
    upf|trex|receiver) ;;
    *) usage; fatal "Missing or invalid --setup role. Use upf, trex, or receiver." ;;
  esac

  apply_role_defaults
  print_effective_topology
}

apt_install_common() {
  log "Running apt-get update and installing common packages"
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    git \
    make \
    curl \
    wget \
    jq \
    net-tools \
    tcpdump \
    ethtool \
    pciutils \
    iproute2 \
    ca-certificates \
    python3 \
    python3-pip \
    docker.io \
    docker-compose-v2 \
    docker-buildx \
    libibverbs1 \
    ibverbs-providers \
    librdmacm1 \
    libmlx5-1 \
    linux-modules-extra-"$(uname -r)" || true

  systemctl enable --now docker || true
}

load_rdma_modules() {
  log "Loading RDMA and Mellanox modules"
  modprobe ib_uverbs || warn "Could not load ib_uverbs"
  modprobe rdma_ucm || warn "Could not load rdma_ucm"
  modprobe mlx5_ib || warn "Could not load mlx5_ib"
  ldconfig || true
}

validate_rdma_stack() {
  log "Validating RDMA and mlx5 userspace"
  if [[ -e /lib/x86_64-linux-gnu/libmlx5.so.1 ]]; then
    strings /lib/x86_64-linux-gnu/libmlx5.so.1 | grep -q MLX5_1.24 \
      && log "MLX5_1.24 symbol found in libmlx5.so.1" \
      || warn "MLX5_1.24 symbol not found in /lib/x86_64-linux-gnu/libmlx5.so.1"
  else
    warn "/lib/x86_64-linux-gnu/libmlx5.so.1 not found"
  fi

  if [[ -d /dev/infiniband ]]; then
    ls -l /dev/infiniband || true
  else
    warn "/dev/infiniband not found"
  fi

  if command -v ibv_devinfo >/dev/null 2>&1; then
    ibv_devinfo || warn "ibv_devinfo returned a non-zero status"
  else
    warn "ibv_devinfo not installed"
  fi
}

basic_reachability_tests() {
  log "Running basic reachability checks for role ${ROLE}"

  case "${ROLE}" in
    receiver)
      ip -br addr show "${N6_IF}" || true
      ping -c 2 -W 1 "${UPF_N6_IP}" || warn "Receiver could not ping UPF N6 ${UPF_N6_IP}. This can be normal if UPF is not configured yet."
      ;;
    upf)
      ip -br addr show "${N3_IF}" "${N6_IF}" "${CTRL_IF}" || true
      ping -c 2 -W 1 "${TREX_N3_IP}" || warn "UPF could not ping TRex N3 ${TREX_N3_IP}. This can be normal if TRex is not configured yet or the interface is DPDK-owned."
      ping -c 2 -W 1 "${RECEIVER_N6_IP}" || warn "UPF could not ping receiver N6 ${RECEIVER_N6_IP}. This can be normal if receiver is not configured yet."
      ping -c 2 -W 1 "${TREX_CTRL_IP}" || warn "UPF could not ping TRex PFCP/control ${TREX_CTRL_IP}. This can be normal if TRex is not configured yet."
      ;;
    trex)
      ip -br addr show "${N3_IF}" "${CTRL_IF}" || true
      ping -c 2 -W 1 "${UPF_N3_IP}" || warn "TRex could not ping UPF N3 ${UPF_N3_IP}. This can be normal if UPF is not configured yet."
      ping -c 2 -W 1 "${UPF_CTRL_IP}" || warn "TRex could not ping UPF PFCP/control ${UPF_CTRL_IP}. This can be normal if UPF is not configured yet."
      ;;
  esac
}

install_ofed_userspace() {
  [[ "${INSTALL_OFED}" == "true" ]] || { log "Skipping MLNX OFED installation"; return; }

  log "Installing MLNX OFED userspace"
  mkdir -p /tmp/preof-ofed
  cd /tmp/preof-ofed
  if [[ ! -f "${MLNX_OFED_URL##*/}" ]]; then
    wget -q --show-progress "${MLNX_OFED_URL}"
  fi
  rm -rf "${MLNX_OFED_DIR}"
  tar xzf "${MLNX_OFED_URL##*/}"
  cd "${MLNX_OFED_DIR}"
  ./mlnxofedinstall --user-space-only --without-fw-update || warn "MLNX OFED installer returned a non-zero status. Check logs above."
  ldconfig

  modprobe ib_uverbs || true
  modprobe rdma_ucm || true
  modprobe mlx5_ib || true

  log "OFED validation output"
  strings /lib/x86_64-linux-gnu/libmlx5.so.1 2>/dev/null | grep MLX5_1.24 || warn "MLX5_1.24 not found in libmlx5.so.1"
  ls -l /dev/infiniband 2>/dev/null || warn "/dev/infiniband not present"
}

configure_hugepages() {
  log "Configuring hugepages: ${HUGEPAGES}"
  mkdir -p /dev/hugepages
  mount -t hugetlbfs nodev /dev/hugepages 2>/dev/null || true
  sysctl -w vm.nr_hugepages="${HUGEPAGES}"
  echo "vm.nr_hugepages=${HUGEPAGES}" > /etc/sysctl.d/90-preof-hugepages.conf
  grep -i Huge /proc/meminfo || true
}

interface_exists() {
  ip link show dev "$1" >/dev/null 2>&1
}

configure_ip() {
  local iface="$1"
  local ip_cidr="$2"
  local label="$3"

  interface_exists "${iface}" || fatal "Interface ${iface} for ${label} not found. Use --n3-if/--n6-if/--ctrl-if with the real Linux name."

  log "Configuring ${label}: ${iface} -> ${ip_cidr}"
  ip link set "${iface}" up
  ip addr flush dev "${iface}"
  ip addr add "${ip_cidr}" dev "${iface}"
  ip link set "${iface}" mtu 1500

  # For reproducible software tests, disabling offloads can make captures easier to interpret.
  ethtool -K "${iface}" gro off gso off tso off rx off tx off 2>/dev/null || true
  ip -br addr show "${iface}"
}

iface_mac() {
  cat "/sys/class/net/$1/address"
}

iface_pci_short() {
  local iface="$1"
  local pci
  pci="$(basename "$(readlink -f "/sys/class/net/${iface}/device")")"
  echo "${pci#0000:}"
}

persist_netplan_for_role() {
  [[ "${PERSIST_NETPLAN}" == "true" ]] || return

  log "Writing netplan persistence for role ${ROLE}"
  case "${ROLE}" in
    receiver)
      cat > /etc/netplan/60-preof-testbed.yaml <<EOF_NETPLAN
network:
  version: 2
  ethernets:
    ${N6_IF}:
      addresses: [${RECEIVER_N6_IP}/24]
      mtu: 1500
EOF_NETPLAN
      ;;
    upf)
      cat > /etc/netplan/60-preof-testbed.yaml <<EOF_NETPLAN
network:
  version: 2
  ethernets:
    ${N3_IF}:
      addresses: [${UPF_N3_IP}/24]
      mtu: 1500
    ${N6_IF}:
      addresses: [${UPF_N6_IP}/24]
      mtu: 1500
    ${CTRL_IF}:
      addresses: [${UPF_CTRL_IP}/24]
      mtu: 1500
EOF_NETPLAN
      ;;
    trex)
      cat > /etc/netplan/60-preof-testbed.yaml <<EOF_NETPLAN
network:
  version: 2
  ethernets:
    ${N3_IF}:
      addresses: [${TREX_N3_IP}/24]
      mtu: 1500
    ${CTRL_IF}:
      addresses: [${TREX_CTRL_IP}/24]
      mtu: 1500
EOF_NETPLAN
      ;;
  esac
  netplan apply || warn "netplan apply failed. The live ip configuration was already applied."
}

discover_neighbor_mac() {
  local iface="$1"
  local ip="$2"
  local supplied_mac="$3"

  if [[ -n "${supplied_mac}" ]]; then
    echo "${supplied_mac}"
    return
  fi

  ping -c 1 -W 1 -I "${iface}" "${ip}" >/dev/null 2>&1 || true
  ip neigh show "${ip}" dev "${iface}" | awk '{print $5}' | head -n1
}

setup_receiver() {
  apt_install_common
  install_ofed_userspace
  load_rdma_modules
  validate_rdma_stack
  configure_hugepages

  configure_ip "${N6_IF}" "${RECEIVER_N6_IP}/24" "receiver N6"
  persist_netplan_for_role
  basic_reachability_tests

  log "Installing Python packages useful for receiver-side dedup experiments"
  python3 -m pip install --upgrade pip >/dev/null 2>&1 || true
  python3 -m pip install scapy pandas >/dev/null 2>&1 || true

  mkdir -p "${WORKDIR}/receiver"
  cat > "${WORKDIR}/receiver/README.txt" <<EOF_RX
Receiver host prepared.

N6 interface: ${N6_IF}
N6 IP:        ${RECEIVER_N6_IP}
N6 MAC:       $(iface_mac "${N6_IF}")

Use this MAC on the UPF if ARP discovery is not available:
  --receiver-n6-mac $(iface_mac "${N6_IF}")

Suggested capture check:
  sudo tcpdump -i ${N6_IF} -nn udp port 5555
EOF_RX

  log "Receiver setup complete"
  cat "${WORKDIR}/receiver/README.txt"
}

setup_upf_configs() {
  mkdir -p "${BESS_WORKDIR}/config"

  cat > "${BESS_WORKDIR}/config/upf-dpdk-local.jsonc" <<EOF_UPF_JSON
{
  "mode": "dpdk",
  "log_level": "info",
  "max_sessions": 1024,
  "table_sizes": {
    "pdrLookup": 1024,
    "flowMeasure": 1024,
    "appQERLookup": 1024,
    "sessionQERLookup": 1024,
    "farLookup": 1024
  },
  "access": {
    "ifname": "${N3_IF}"
  },
  "core": {
    "ifname": "${N6_IF}"
  },
  "measure_upf": true,
  "measure_flow": true,
  "enable_notify_bess": false,
  "enable_end_marker": false,
  "workers": 1,
  "read_timeout": 25,
  "cpiface": {
    "dnn": "internet",
    "hostname": "upf",
    "http_port": "8080",
    "enable_ue_ip_alloc": false,
    "ue_ip_pool": "10.250.0.0/24"
  },
  "slice_rate_limit_config": {
    "n6_bps": 1000000000,
    "n6_burst_bytes": 12500000,
    "n3_bps": 1000000000,
    "n3_burst_bytes": 12500000
  }
}
EOF_UPF_JSON

  cat > "${BESS_WORKDIR}/config/docker-compose-dpdk.yml" <<'EOF_COMPOSE'
services:
  bess:
    image: upf-bess:2.4.2-dev-mlx5
    container_name: bess
    network_mode: host
    privileged: true
    cap_add:
      - IPC_LOCK
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_NICE
      - SYS_RESOURCE
    volumes:
      - ./upf-dpdk-local.jsonc:/opt/bess/bessctl/conf/upf.jsonc
      - /sys:/sys
      - /sys/devices/system/node:/sys/devices/system/node
      - /lib/modules:/lib/modules
      - /dev/hugepages:/dev/hugepages
      - /dev/infiniband:/dev/infiniband
    command: >
      -grpc-url=0.0.0.0:10514

  pfcpiface:
    image: upf-pfcp:2.4.2-dev
    container_name: pfcpiface
    network_mode: host
    cap_add:
      - NET_ADMIN
    depends_on:
      - bess
    volumes:
      - ./upf-dpdk-local.jsonc:/conf/upf.jsonc
    command: >
      -config /conf/upf.jsonc
EOF_COMPOSE

  cat > "${BESS_WORKDIR}/config/Dockerfile.bess-mlx5" <<'EOF_DOCKER'
FROM upf-bess:2.4.2-dev

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    --no-install-recommends \
    libibverbs1 \
    ibverbs-providers \
    librdmacm1 \
    libmlx5-1 \
    libnl-3-200 \
    libnl-route-3-200 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN set -e; \
    mkdir -p /opt/bess/lib/dpdk-pmds; \
    for pat in librte_common_mlx5 librte_net_mlx5; do \
      found=0; \
      for f in /usr/local/lib/x86_64-linux-gnu/${pat}.so*; do \
        if [ -f "$f" ]; then \
          ln -sf "$f" /opt/bess/lib/dpdk-pmds/; \
          found=1; \
        fi; \
      done; \
      if [ "$found" -eq 0 ]; then \
        echo "Missing ${pat}" >&2; \
        exit 1; \
      fi; \
    done; \
    ldconfig; \
    echo "MLX5 PMDs enabled:"; \
    ls -l /opt/bess/lib/dpdk-pmds | grep mlx5
EOF_DOCKER
}

setup_upf() {
  apt_install_common
  install_ofed_userspace
  load_rdma_modules
  validate_rdma_stack
  configure_hugepages

  configure_ip "${N3_IF}" "${UPF_N3_IP}/24" "UPF N3/access"
  configure_ip "${N6_IF}" "${UPF_N6_IP}/24" "UPF N6/core"
  configure_ip "${CTRL_IF}" "${UPF_CTRL_IP}/24" "UPF PFCP/control"
  persist_netplan_for_role
  basic_reachability_tests

  log "Cloning OMEC repositories if needed"
  mkdir -p "${BESS_WORKDIR}"
  cd "${BESS_WORKDIR}"
  [[ -d upf ]] || git clone https://github.com/omec-project/upf.git
  [[ -d bess ]] || git clone https://github.com/omec-project/bess.git

  log "Building BESS-UPF Docker images"
  cd "${BESS_WORKDIR}/upf"
  make DOCKER_BUILD_ARGS="--network=host" docker-build

  setup_upf_configs

  log "Building mlx5-enabled BESS image"
  cd "${BESS_WORKDIR}/config"
  docker build --network=host -f Dockerfile.bess-mlx5 -t upf-bess:2.4.2-dev-mlx5 .

  local rx_mac
  rx_mac="$(discover_neighbor_mac "${N6_IF}" "${RECEIVER_N6_IP}" "${RECEIVER_N6_MAC}")"
  if [[ -z "${rx_mac}" ]]; then
    warn "Could not discover receiver N6 MAC. Re-run with --receiver-n6-mac MAC before starting experiments."
  else
    log "Installing static N6 neighbor and route to receiver ${RECEIVER_N6_IP}, MAC ${rx_mac}"
    ip neigh replace "${RECEIVER_N6_IP}" lladdr "${rx_mac}" dev "${N6_IF}" nud permanent
    ip route replace "${RECEIVER_N6_IP}/32" via "${RECEIVER_N6_IP}" dev "${N6_IF}" onlink
  fi

  if [[ "${START_UPF}" == "true" ]]; then
    log "Starting BESS-UPF DPDK containers"
    cd "${BESS_WORKDIR}/config"
    docker rm -f pfcpiface bess-routectl bess 2>/dev/null || true
    docker compose -f docker-compose-dpdk.yml up -d bess
    sleep 3
    docker logs bess --tail 80 || true

    log "Loading UPF pipeline"
    docker exec bess bash -lc 'cd /opt/bess/bessctl && ./bessctl run up4'

    log "Starting pfcpiface"
    docker compose -f docker-compose-dpdk.yml up -d pfcpiface

    log "Starting route controller"
    docker rm -f bess-routectl 2>/dev/null || true
    docker run --name bess-routectl -td --restart unless-stopped \
      --net host \
      --pid container:bess \
      --entrypoint python3 \
      -v "${BESS_WORKDIR}/upf/conf/route_control.py:/route_control.py" \
      upf-bess:2.4.2-dev-mlx5 \
      /route_control.py -i "${N3_IF}" "${N6_IF}"

    sleep 3
    docker logs bess-routectl --tail 30 || true
  fi

  cat > "${BESS_WORKDIR}/config/README-next-commands.txt" <<EOF_UPF_NEXT
UPF host prepared.

Interfaces:
  N3/access:      ${N3_IF}, ${UPF_N3_IP}, MAC $(iface_mac "${N3_IF}"), PCI $(iface_pci_short "${N3_IF}")
  N6/core:        ${N6_IF}, ${UPF_N6_IP}, MAC $(iface_mac "${N6_IF}"), PCI $(iface_pci_short "${N6_IF}")
  PFCP/control:  ${CTRL_IF}, ${UPF_CTRL_IP}, MAC $(iface_mac "${CTRL_IF}")

Use this UPF N3 MAC on the TRex host if ARP discovery is not available:
  --upf-n3-mac $(iface_mac "${N3_IF}")

After you start your patched pfcpsim on the TRex host, configure it with:
  pfcpctl -s localhost:12345 service configure --n3-addr ${UPF_N3_IP} --remote-peer-addr ${UPF_CTRL_IP}
  pfcpctl -s localhost:12345 service associate

Then create sessions using your patched per-slice MBR flags.

Validation:
  curl -s http://127.0.0.1:8080/metrics | grep pfcp_sessions
  docker exec bess /opt/bess/bessctl/bessctl show port
  docker exec bess /opt/bess/bessctl/bessctl show module ${N6_IF}Routes
EOF_UPF_NEXT

  log "UPF setup complete"
  cat "${BESS_WORKDIR}/config/README-next-commands.txt"
}

setup_trex_profile_dir() {
  mkdir -p "${TREX_DIR}/automation/preof"
  cat > "${TREX_DIR}/automation/preof/README.txt" <<EOF_TREX_README
TRex host prepared.

This setup intentionally does not clone pfcpsim.
Use your patched repository or image.

Typical patched pfcpsim startup:
  sudo docker run --rm -d --network host --name pfcpsim pfcpsim:patched -p 12345 --interface ${CTRL_IF}

Typical PFCP configuration:
  sudo docker exec pfcpsim pfcpctl -s localhost:12345 service configure --n3-addr ${UPF_N3_IP} --remote-peer-addr ${UPF_CTRL_IP}
  sudo docker exec pfcpsim pfcpctl -s localhost:12345 service associate
EOF_TREX_README
}

write_trex_cfg() {
  local n3_pci n3_src_mac dest_mac
  n3_pci="$(iface_pci_short "${N3_IF}")"
  n3_src_mac="$(iface_mac "${N3_IF}")"

  dest_mac="$(discover_neighbor_mac "${N3_IF}" "${UPF_N3_IP}" "${UPF_N3_MAC}")"
  if [[ -z "${dest_mac}" ]]; then
    fatal "Could not discover UPF N3 MAC. Re-run with --upf-n3-mac MAC."
  fi

  if [[ -n "${TREX_PORT2_IF}" ]]; then
    interface_exists "${TREX_PORT2_IF}" || fatal "Optional TRex port2 interface ${TREX_PORT2_IF} not found"
    [[ -n "${TREX_PORT2_DST_MAC}" ]] || fatal "When using --trex-port2-if, also pass --trex-port2-dst-mac"
    local p2_pci p2_src_mac
    p2_pci="$(iface_pci_short "${TREX_PORT2_IF}")"
    p2_src_mac="$(iface_mac "${TREX_PORT2_IF}")"
    cat > /etc/trex_cfg.yaml <<EOF_TREX_CFG2
- version: 2
  interfaces: ['${n3_pci}', '${p2_pci}']
  port_mtu: 1500
  port_info:
      - dest_mac: ${dest_mac}
        src_mac:  ${n3_src_mac}
      - dest_mac: ${TREX_PORT2_DST_MAC}
        src_mac:  ${p2_src_mac}

  platform:
      master_thread_id: 0
      latency_thread_id: 1
      dual_if:
        - socket: 0
          threads: [2,3,4,5,6,7,8,9]
EOF_TREX_CFG2
  else
    cat > /etc/trex_cfg.yaml <<EOF_TREX_CFG1
- version: 2
  interfaces: ['${n3_pci}']
  port_mtu: 1500
  port_info:
      - dest_mac: ${dest_mac}
        src_mac:  ${n3_src_mac}

  platform:
      master_thread_id: 0
      latency_thread_id: 1
      dual_if:
        - socket: 0
          threads: [2,3,4,5,6,7,8,9]
EOF_TREX_CFG1
  fi

  log "Generated /etc/trex_cfg.yaml"
  cat /etc/trex_cfg.yaml

  if [[ -z "${TREX_PORT2_IF}" ]]; then
    warn "Generated a one-port TRex configuration. If your TRex binary refuses one port, rerun with --trex-port2-if enp8s0np0 and a valid --trex-port2-dst-mac."
  fi
}

setup_trex() {
  apt_install_common
  install_ofed_userspace
  load_rdma_modules
  validate_rdma_stack
  configure_hugepages

  configure_ip "${N3_IF}" "${TREX_N3_IP}/24" "TRex N3"
  configure_ip "${CTRL_IF}" "${TREX_CTRL_IP}/24" "TRex PFCP/control"
  if [[ -n "${TREX_PORT2_IF}" ]]; then
    ip link set "${TREX_PORT2_IF}" up
    ip link set "${TREX_PORT2_IF}" mtu 1500
  fi
  persist_netplan_for_role
  basic_reachability_tests

  log "Installing TRex ${TREX_VERSION}"
  mkdir -p /opt/trex /tmp/preof-trex
  cd /tmp/preof-trex
  if [[ ! -f "${TREX_VERSION}.tar.gz" ]]; then
    wget --no-check-certificate -O "${TREX_VERSION}.tar.gz" "${TREX_TARBALL_URL}"
  fi
  tar -xzf "${TREX_VERSION}.tar.gz" -C /opt/trex
  test -x "${TREX_DIR}/t-rex-64" || fatal "TRex binary not found at ${TREX_DIR}/t-rex-64"

  modprobe ib_uverbs || true
  modprobe rdma_ucm || true
  modprobe mlx5_ib || true

  write_trex_cfg
  setup_trex_profile_dir

  cat > "${TREX_DIR}/automation/preof/host-summary.txt" <<EOF_TREX_SUMMARY
TRex host prepared.

N3 interface:      ${N3_IF}, ${TREX_N3_IP}, MAC $(iface_mac "${N3_IF}"), PCI $(iface_pci_short "${N3_IF}")
PFCP/control:      ${CTRL_IF}, ${TREX_CTRL_IP}, MAC $(iface_mac "${CTRL_IF}")
TRex config:       /etc/trex_cfg.yaml
TRex directory:    ${TREX_DIR}

Start TRex:
  cd ${TREX_DIR}
  sudo ./t-rex-64 -i --no-ofed-check -c 8

For software latency mode:
  cd ${TREX_DIR}
  sudo ./t-rex-64 -i --software --no-ofed-check -c 8
EOF_TREX_SUMMARY

  log "TRex setup complete"
  cat "${TREX_DIR}/automation/preof/host-summary.txt"
}

main() {
  require_root
  parse_args "$@"

  case "${ROLE}" in
    receiver) setup_receiver ;;
    upf) setup_upf ;;
    trex) setup_trex ;;
  esac
}

main "$@"

